### PR TITLE
[WIP][lostcol] First cut

### PR DESCRIPTION
**Pull request by owjjh**
## ADD:
- Schema/lostcol/character.yml
- Schema/lostcol/skill.yml

### CODE REVIEW

**Comment by GorkamWorka** [comment]
Good first batch , these yml files seem ok
Need help for the template part ?

**Comment by owjjh** [comment]
I was under the impression that there was a default that would be used.  If that is not the case then I will take a look at the template and any pointers would be appreciated!

**Comment by GorkamWorka** [comment]
no there is not "default template " for presentation.
The Yml file defines the data-structure, which in turn define the default form in the Editor mode.
But if you want your block to be useful you need to have a presentation template to define how it's displayed on the Presentation mode.

Exemple of such template can be found in  Display directory

**Comment by owjjh** [comment]
I have added basic template support and one more data type.

Am I correct in assuming that when a character gets created they can have multiple of a block type?  So one character can have multiple skills and scars in my case?

**Pull request merged**
